### PR TITLE
Port to Python 3

### LINKED ISSUE #403: Python 3 version

### PR DESCRIPTION
**Pull request by zklaus**
This is my latest attempt at porting ece2cmor to Python 3.

A lot seems to work already, but I am running into some problems that I need help with.
First of all, I cannot download the test data because the git lfs quota is exhausted.
Does anyone have insight into when and how it will be replenished?

Fixes #403.

### CODE REVIEW

**Comment by zklaus** [comment]
I think this is ready. @treerink, could you do one of your extended tests before we try it out IRL?

**Comment by goord** [comment]
@treerink you want to run your tests once more? It would be good to merge this and prepare a new release maybe...

**Comment by zklaus** [comment]
Any news on this, @treerink?

**Comment by zklaus** [comment]
In a technical working group (TWG) discussion we got the advice from @JanStreffing to avoid cdo versions from 2.0.0 to 2.0.4, inclusive.

**Comment by JanStreffing** [comment]
See also: https://code.mpimet.mpg.de/issues/10628

**Comment by zklaus** [comment]
Moved comment from @treerink here: https://github.com/EC-Earth/ece2cmor3/issues/737#issue-1192941095

I have freshly installed `ece2cmor3-py3` on my ubuntu laptop by using `mamba` (this uses `python3.10`) which is thus based on the `python-3-klaus` branch.

In an active environment I am able to run very basic stuff like: `cdo -V` (v2.05), `ece2cmor3 -h`, `drq -h`.

The first thing I try is to run `genecec` (I had ported `genecec` earlier to python3 and this was at least at that time working). In the new branch probably some more changes have been made, so let's test.

I get the following error now:
```
Traceback (most recent call last):
  File "/home/thomas/cmorize/ece2cmor3/ece2cmor3/scripts/./genecec.py", line 27, in <module>
    dq = dreq.loadDreq()
  File "/home/thomas/mamba/envs/ece2cmor3-py3/lib/python3.10/site-packages/dreqPy/dreq.py", line 1020, in __init__
    self.c = config( thisdoc=dreqXML, configdoc=configdoc, useShelve=useShelve,strings=strings,manifest=manifest,configOnly=configOnly,lxml=lxml)
  File "/home/thomas/mamba/envs/ece2cmor3-py3/lib/python3.10/site-packages/dreqPy/dreq.py", line 581, in __init__
    self.__read__(d, c)
  File "/home/thomas/mamba/envs/ece2cmor3-py3/lib/python3.10/site-packages/dreqPy/dreq.py", line 657, in __read__
    self.parent_map = dict((c, p) for p in root.getiterator() for c in p)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```
I have not dived into it yet, first asking @zklaus if you have immediately an idea about this. Maybe [here](https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying) the direction of the answer can be found.

**Comment by zklaus** [comment]
Thanks @treerink, this is due to Dreqpy not being compatible with Python 3.9+ as explained in the Stackoverflow post you linked above. I am patching this in the conda-forge package, but in the meantime you should be able to proceed by downgrading Python to Python 3.8.

**Comment by zklaus** [comment]
Alright, the conda-forge package was fixed in conda-forge/dreqpy-feedstock#1. It should take about 2hr for the new package to trickle through to the CDN and then everything should work with Python 3.9+ as well.

**Comment by treerink** [comment]
Ok thanks (some expert knowledge there I see), so in two hours from now I guess I have to do a:
```
mamba update -y --name base mamba
```
and to recreate my ece2cmor3-py3 environment, etc?

**Comment by zklaus** [comment]
No need to update mamba. It should be enough to update the dreqpy package, so
```
mamba update -n ece2cmor3-py3 dreqpy
```
should do the trick, imho.

**Comment by treerink** [comment]
As discussed this morning, I am using from the `scripts` dir, the following command after drq is working now to test the next step:
```
drq2file_def --drq cmip6-data-request/cmip6-data-request-CMIP.DCPP.LS3MIP.ScenarioMIP.CORDEX.DynVarMIP.VIACSAB-ssp126-t1-p1/cmvme_cm.co.dc.dy.ls.sc.vi_ssp126_1_1.xlsx
```
However, I realise now, this requires first some `drq` call, I have to figure out which one (in my case I have them form an earlier call of `genecec`).

**Comment by treerink** [comment]
Ok you first need to run:
```
drq -m CMIP,DCPP,LS3MIP,ScenarioMIP,CORDEX,DynVarMIP,VIACSAB -e ssp126 -t 1 -p 1 --xls --xlsDir mip6-data-request/cmip6-data-request-CMIP.DCPP.LS3MIP.ScenarioMIP.CORDEX.DynVarMIP.VIACSAB-ssp126-t1-p1
```
to have that xlsx in place.

**Comment by zklaus** [comment]
There was a typo: the parameter is called `values_only`, but I had accidentally written `value_only`. This is now fixed.

**Comment by zklaus** [comment]
@treerink, did you make any progress on the tests?

**Comment by goord** [comment]
Let's merge and create a new release

**Comment by zklaus** [comment]
Happy to see this moving again :smile: Thanks, @treerink!
